// apps/desktop-ui/src/App.tsx
import { Activity, ListChecks, Rocket, Settings as SettingsIcon } from "lucide-react";
import { Layout, Menu, Typography } from "antd";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  cancelLocalRun,
  decideLocalApproval,
  fetchCloudRuns,
  fetchHealth,
  fetchLocalPendingApprovals,
  fetchLocalRun,
  fetchLocalRuns,
  login,
  type CloudRunListItem,
  type HealthResult,
  type LocalPendingApproval,
  type LocalRunDetail,
} from "./lib/api.ts";
import {
  clearToken,
  getAccessToken,
  getServerAddress,
  getUsername,
  saveServerAddress,
  saveToken,
} from "./lib/settings.ts";
import {
  invokeRunnerStatus,
  invokeStartRunner,
  invokeStopRunner,
  isTauri,
  type RunnerInfo,
} from "./lib/tauri.ts";
import { OverviewPage } from "./pages/Overview.tsx";
import { RunsPage } from "./pages/RunsPage.tsx";
import { ApprovalsPage } from "./pages/ApprovalsPage.tsx";
import { SettingsPage } from "./pages/SettingsPage.tsx";

const { Sider, Content } = Layout;

type PageKey = "overview" | "runs" | "approvals" | "settings";

const NAV_ITEMS: Array<{ key: PageKey; icon: typeof Rocket; label: string }> = [
  { key: "overview", icon: Rocket, label: "概览" },
  { key: "runs", icon: Activity, label: "Runs" },
  { key: "approvals", icon: ListChecks, label: "审批" },
  { key: "settings", icon: SettingsIcon, label: "设置" },
];

/** 桌面端全局状态 + 动作（M1/M2 逻辑层与 lib/ 一致，仅视图层为 React 重写）。 */
export function useAppState() {
  const [page, setPage] = useState<PageKey>("overview");
  const [serverInput, setServerInput] = useState(getServerAddress());
  const [health, setHealth] = useState<HealthResult | null>(null);
  const [healthError, setHealthError] = useState("");
  const [checkingHealth, setCheckingHealth] = useState(false);
  const [username, setUsername] = useState(getUsername());
  const [password, setPassword] = useState("");
  const [authError, setAuthError] = useState("");
  const [loggingIn, setLoggingIn] = useState(false);
  const [loggedIn, setLoggedIn] = useState(getAccessToken() !== null);

  const [cloudRuns, setCloudRuns] = useState<CloudRunListItem[]>([]);
  const [cloudRunsError, setCloudRunsError] = useState("");
  const [loadingCloudRuns, setLoadingCloudRuns] = useState(false);

  const [runner, setRunner] = useState<RunnerInfo | null>(null);
  const [workspaceRoot, setWorkspaceRoot] = useState("");
  const [trustedMode, setTrustedMode] = useState(false);
  const [runnerBusy, setRunnerBusy] = useState(false);

  const [localRuns, setLocalRuns] = useState<CloudRunListItem[]>([]);
  const [localRunsError, setLocalRunsError] = useState("");
  const [loadingLocalRuns, setLoadingLocalRuns] = useState(false);

  const [pendingApprovals, setPendingApprovals] = useState<LocalPendingApproval[]>([]);
  const [loadingApprovals, setLoadingApprovals] = useState(false);
  const [actingApprovalId, setActingApprovalId] = useState<string | null>(null);

  const [selectedRunId, setSelectedRunId] = useState<string | null>(null);
  const [selectedRun, setSelectedRun] = useState<LocalRunDetail | null>(null);
  const [runDetailError, setRunDetailError] = useState("");
  const [loadingDetail, setLoadingDetail] = useState(false);
  const [cancellingRun, setCancellingRun] = useState(false);

  const desktop = useMemo(() => isTauri(), []);
  const runnerEndpoint = useMemo(
    () =>
      runner?.running === true && runner.baseUrl !== null
        ? { baseUrl: runner.baseUrl, token: runner.token }
        : null,
    [runner],
  );

  const checkHealth = useCallback(async (): Promise<void> => {
    setCheckingHealth(true);
    setHealthError("");
    try {
      saveServerAddress(serverInput);
      setHealth(await fetchHealth(serverInput));
    } catch (error) {
      setHealth(null);
      setHealthError(String(error));
    } finally {
      setCheckingHealth(false);
    }
  }, [serverInput]);

  const doLogin = useCallback(async (): Promise<void> => {
    setLoggingIn(true);
    setAuthError("");
    try {
      saveServerAddress(serverInput);
      const result = await login(username, password);
      saveToken(result.accessToken, result.username);
      setLoggedIn(true);
      setPassword("");
    } catch (error) {
      setAuthError(String(error));
    } finally {
      setLoggingIn(false);
    }
  }, [serverInput, username, password]);

  const logout = useCallback((): void => {
    clearToken();
    setLoggedIn(false);
    setCloudRuns([]);
  }, []);

  const loadCloudRuns = useCallback(async (): Promise<void> => {
    setLoadingCloudRuns(true);
    setCloudRunsError("");
    try {
      setCloudRuns(await fetchCloudRuns());
    } catch (error) {
      setCloudRunsError(String(error));
    } finally {
      setLoadingCloudRuns(false);
    }
  }, []);

  const loadLocalRuns = useCallback(async (): Promise<void> => {
    if (runnerEndpoint === null) return;
    setLoadingLocalRuns(true);
    setLocalRunsError("");
    try {
      setLocalRuns(await fetchLocalRuns(runnerEndpoint));
    } catch (error) {
      setLocalRunsError(String(error));
    } finally {
      setLoadingLocalRuns(false);
    }
  }, [runnerEndpoint]);

  const loadApprovals = useCallback(async (): Promise<void> => {
    if (runnerEndpoint === null || runner?.trusted !== true) return;
    setLoadingApprovals(true);
    try {
      setPendingApprovals(await fetchLocalPendingApprovals(runnerEndpoint));
    } catch {
      // Trusted Local Mode 半途关闭等场景：静默置空（禁用态由 trusted 控制）
      setPendingApprovals([]);
    } finally {
      setLoadingApprovals(false);
    }
  }, [runnerEndpoint, runner?.trusted]);

  const decide = useCallback(
    async (id: string, decision: "approved" | "rejected"): Promise<void> => {
      if (runnerEndpoint === null) return;
      setActingApprovalId(id);
      try {
        await decideLocalApproval(runnerEndpoint, id, decision);
        await loadApprovals();
        void loadLocalRuns();
      } finally {
        setActingApprovalId(null);
      }
    },
    [runnerEndpoint, loadApprovals, loadLocalRuns],
  );

  const refreshRunner = useCallback(async (): Promise<void> => {
    const info = await invokeRunnerStatus();
    setRunner(info);
    if (info?.running === true && info.baseUrl !== null) {
      void loadLocalRuns();
      void loadApprovals();
    }
  }, [loadLocalRuns, loadApprovals]);

  const startRunner = useCallback(async (): Promise<void> => {
    setRunnerBusy(true);
    try {
      const info = await invokeStartRunner(workspaceRoot, trustedMode);
      setRunner(info);
      if (info?.running === true && info.baseUrl !== null) {
        void loadLocalRuns();
        void loadApprovals();
      }
    } finally {
      setRunnerBusy(false);
    }
  }, [workspaceRoot, trustedMode, loadLocalRuns, loadApprovals]);

  const stopRunner = useCallback(async (): Promise<void> => {
    setRunnerBusy(true);
    try {
      await invokeStopRunner();
      setRunner(await invokeRunnerStatus());
      setLocalRuns([]);
      setLocalRunsError("");
      setPendingApprovals([]);
    } finally {
      setRunnerBusy(false);
    }
  }, []);

  const openRunDetail = useCallback(
    async (id: string): Promise<void> => {
      if (runnerEndpoint === null) return;
      setSelectedRunId(id);
      setLoadingDetail(true);
      setRunDetailError("");
      try {
        setSelectedRun(await fetchLocalRun(runnerEndpoint, id));
      } catch (error) {
        setSelectedRun(null);
        setRunDetailError(String(error));
      } finally {
        setLoadingDetail(false);
      }
    },
    [runnerEndpoint],
  );

  const cancelRun = useCallback(
    async (id: string): Promise<void> => {
      if (runnerEndpoint === null) return;
      setCancellingRun(true);
      try {
        setSelectedRun(await cancelLocalRun(runnerEndpoint, id));
        void loadLocalRuns();
      } finally {
        setCancellingRun(false);
      }
    },
    [runnerEndpoint, loadLocalRuns],
  );

  useEffect(() => {
    void refreshRunner();
  }, [refreshRunner]);

  return {
    page,
    setPage,
    serverInput,
    setServerInput,
    health,
    healthError,
    checkingHealth,
    checkHealth,
    username,
    setUsername,
    password,
    setPassword,
    authError,
    loggingIn,
    loggedIn,
    doLogin,
    logout,
    cloudRuns,
    cloudRunsError,
    loadingCloudRuns,
    loadCloudRuns,
    runner,
    workspaceRoot,
    setWorkspaceRoot,
    trustedMode,
    setTrustedMode,
    runnerBusy,
    startRunner,
    stopRunner,
    localRuns,
    localRunsError,
    loadingLocalRuns,
    loadLocalRuns,
    pendingApprovals,
    loadingApprovals,
    loadApprovals,
    actingApprovalId,
    decide,
    selectedRunId,
    selectedRun,
    runDetailError,
    loadingDetail,
    openRunDetail,
    cancellingRun,
    cancelRun,
    desktop,
  };
}

export type AppState = ReturnType<typeof useAppState>;

export default function App() {
  const state = useAppState();
  const { page } = state;

  return (
    <Layout className="h-full" style={{ background: "#060609" }}>
      <Sider width={216} style={{ background: "#0A0C10", borderRight: "1px solid #1C2028" }}>
        <div className="flex h-full flex-col">
          <div className="flex items-center gap-2.5 px-4 py-4">
            <div className="flex h-7 w-7 items-center justify-center rounded bg-[#6CFF00] text-sm font-black text-black">
              A
            </div>
            <div className="min-w-0">
              <p className="truncate text-sm font-semibold leading-tight">ADui Forge</p>
              <p className="font-mono text-[10px] text-slate-600">Desktop · v{__APP_VERSION__}</p>
            </div>
          </div>
          <Menu
            mode="inline"
            style={{ background: "transparent", borderInlineEnd: "none", padding: "0 8px" }}
            selectedKeys={[page]}
            onClick={(info) => state.setPage(info.key as PageKey)}
            items={NAV_ITEMS.map((item) => ({
              key: item.key,
              icon: <item.icon size={15} />,
              label: item.label,
            }))}
          />
          <div className="mt-auto border-t border-[#1C2028] px-4 py-3">
            {state.loggedIn ? (
              <div className="flex items-center justify-between">
                <span className="truncate text-xs text-slate-400">{getUsername()}</span>
                <Typography.Link
                  className="text-xs"
                  onClick={() => {
                    state.logout();
                    state.setPage("overview");
                  }}
                >
                  退出
                </Typography.Link>
              </div>
            ) : (
              <span className="text-xs text-slate-600">未登录</span>
            )}
          </div>
        </div>
      </Sider>
      <Content className="overflow-y-auto" style={{ background: "#060609" }}>
        <div className="mx-auto max-w-3xl px-6 py-6">
          {page === "overview" && <OverviewPage state={state} />}
          {page === "runs" && <RunsPage state={state} />}
          {page === "approvals" && <ApprovalsPage state={state} />}
          {page === "settings" && <SettingsPage state={state} />}
        </div>
      </Content>
    </Layout>
  );
}

// apps/desktop-ui/src/App.svelte
<script lang="ts">
  import {
    login,
    fetchCloudRuns,
    fetchHealth,
    fetchLocalRuns,
    fetchLocalRun,
    cancelLocalRun,
    decideLocalApproval,
    fetchLocalPendingApprovals,
    type CloudRunListItem,
    type HealthResult,
    type LocalPendingApproval,
    type LocalRunDetail,
  } from "./lib/api.ts";
  import {
    clearToken,
    getAccessToken,
    getServerAddress,
    getUsername,
    saveServerAddress,
    saveToken,
  } from "./lib/settings.ts";
  import {
    invokeRunnerStatus,
    invokeStartRunner,
    invokeStopRunner,
    isTauri,
    type RunnerInfo,
  } from "./lib/tauri.ts";

  let serverInput = $state(getServerAddress());
  let username = $state(getUsername());
  let password = $state("");

  let health = $state<HealthResult | null>(null);
  let healthError = $state("");
  let checkingHealth = $state(false);
  let authError = $state("");
  let loggingIn = $state(false);
  let loggedIn = $state(getAccessToken() !== null);

  let runs = $state<CloudRunListItem[]>([]);
  let runsError = $state("");
  let loadingRuns = $state(false);

  let runner = $state<RunnerInfo | null>(null);
  let workspaceRoot = $state("");
  let trustedMode = $state(false);
  let runnerBusy = $state(false);

  let localRuns = $state<CloudRunListItem[]>([]);
  let localRunsError = $state("");
  let loadingLocalRuns = $state(false);

  let pendingApprovals = $state<LocalPendingApproval[]>([]);
  let loadingApprovals = $state(false);
  let actingApprovalId = $state<string | null>(null);

  let selectedRunId = $state<string | null>(null);
  let selectedRun = $state<LocalRunDetail | null>(null);
  let runDetailError = $state("");
  let loadingDetail = $state(false);
  let cancellingRun = $state(false);

  const desktop = $derived(isTauri());
  const hasServer = $derived(getServerAddress() !== "");

  const checkHealth = async (): Promise<void> => {
    checkingHealth = true;
    healthError = "";
    try {
      saveServerAddress(serverInput);
      health = await fetchHealth(serverInput);
    } catch (error) {
      health = null;
      healthError = String(error);
    } finally {
      checkingHealth = false;
    }
  };

  const doLogin = async (): Promise<void> => {
    loggingIn = true;
    authError = "";
    try {
      saveServerAddress(serverInput);
      const result = await login(username, password);
      saveToken(result.accessToken, result.username);
      loggedIn = true;
    } catch (error) {
      authError = String(error);
    } finally {
      loggingIn = false;
    }
  };

  const logout = (): void => {
    clearToken();
    loggedIn = false;
    runs = [];
  };

  const loadRuns = async (): Promise<void> => {
    loadingRuns = true;
    runsError = "";
    try {
      runs = await fetchCloudRuns();
    } catch (error) {
      runsError = String(error);
    } finally {
      loadingRuns = false;
    }
  };

  const refreshRunner = async (): Promise<void> => {
    runner = await invokeRunnerStatus();
    if (runner?.running === true && runner.baseUrl !== null) {
      void loadLocalRuns();
      void loadApprovals();
    }
  };

  const loadLocalRuns = async (): Promise<void> => {
    if (runner?.running !== true || runner.baseUrl === null) return;
    loadingLocalRuns = true;
    localRunsError = "";
    try {
      localRuns = await fetchLocalRuns({ baseUrl: runner.baseUrl, token: runner.token });
    } catch (error) {
      localRunsError = String(error);
    } finally {
      loadingLocalRuns = false;
    }
  };

  const loadApprovals = async (): Promise<void> => {
    if (runner?.running !== true || runner.baseUrl === null || runner.trusted !== true) return;
    loadingApprovals = true;
    try {
      pendingApprovals = await fetchLocalPendingApprovals({
        baseUrl: runner.baseUrl,
        token: runner.token,
      });
    } catch {
      // Trusted Local Mode 半途关闭等场景：静默置空（禁用态由 trusted 控制）
      pendingApprovals = [];
    } finally {
      loadingApprovals = false;
    }
  };

  const decide = async (id: string, decision: "approved" | "rejected"): Promise<void> => {
    if (runner?.running !== true || runner.baseUrl === null) return;
    actingApprovalId = id;
    try {
      await decideLocalApproval({ baseUrl: runner.baseUrl, token: runner.token }, id, decision);
      await loadApprovals();
      void loadLocalRuns();
    } finally {
      actingApprovalId = null;
    }
  };

  const openRunDetail = async (id: string): Promise<void> => {
    if (runner?.running !== true || runner.baseUrl === null) return;
    selectedRunId = id;
    loadingDetail = true;
    runDetailError = "";
    try {
      selectedRun = await fetchLocalRun({ baseUrl: runner.baseUrl, token: runner.token }, id);
    } catch (error) {
      selectedRun = null;
      runDetailError = String(error);
    } finally {
      loadingDetail = false;
    }
  };

  const cancelRun = async (id: string): Promise<void> => {
    if (runner?.running !== true || runner.baseUrl === null) return;
    cancellingRun = true;
    try {
      selectedRun = await cancelLocalRun({ baseUrl: runner.baseUrl, token: runner.token }, id);
      void loadLocalRuns();
    } finally {
      cancellingRun = false;
    }
  };

  const startRunner = async (): Promise<void> => {
    runnerBusy = true;
    try {
      runner = await invokeStartRunner(workspaceRoot, trustedMode);
      if (runner?.running === true && runner.baseUrl !== null) {
        void loadLocalRuns();
        void loadApprovals();
      }
    } finally {
      runnerBusy = false;
    }
  };

  const stopRunner = async (): Promise<void> => {
    runnerBusy = true;
    try {
      await invokeStopRunner();
      runner = await invokeRunnerStatus();
      localRuns = [];
      localRunsError = "";
    } finally {
      runnerBusy = false;
    }
  };

  const statusColor = (status: string): string =>
    status === "completed"
      ? "text-[#6CFF00]"
      : status === "failed"
        ? "text-red-400"
        : "text-slate-300";

  // 初始化：恢复 Runner 状态（桌面）与 Runs（已登录时）
  $effect(() => {
    void refreshRunner();
  });
</script>

<div class="flex h-full flex-col">
  <header
    data-tauri-drag-region
    class="flex items-center gap-3 border-b border-[#1C2028] px-5 py-3"
  >
    <div class="flex h-6 w-6 items-center justify-center rounded bg-[#6CFF00] font-black text-black"
      >A</div
    >
    <h1 class="text-sm font-semibold tracking-wide">ADui Forge Desktop</h1>
    <span class="font-mono text-[10px] text-slate-600">v{__APP_VERSION__}</span>
    <div class="ml-auto flex items-center gap-2 text-xs text-slate-400">
      {#if loggedIn}
        <span>{getUsername()}</span>
        <button class="rounded px-2 py-1 hover:bg-[#1C2028]" onclick={logout}>退出</button>
      {:else}
        <span class="text-slate-600">未登录</span>
      {/if}
    </div>
  </header>

  <main class="flex-1 overflow-y-auto p-5">
    <section class="mb-5 rounded-lg border border-[#20242C] bg-[#0D0F13] p-4">
      <h2 class="mb-3 text-xs font-semibold tracking-wider text-slate-500 uppercase">服务器</h2>
      <div class="flex flex-wrap items-center gap-2">
        <input
          class="min-w-80 flex-1 rounded border border-[#292E39] bg-[#111318] px-3 py-1.5 text-sm outline-none focus:border-[#8B51A6]"
          placeholder="http://your-server:3000"
          bind:value={serverInput}
          onchange={() => saveServerAddress(serverInput)}
        />
        <button
          class="rounded border border-[#292E39] px-3 py-1.5 text-sm hover:border-[#6CFF00]/50 disabled:opacity-40"
          disabled={checkingHealth || serverInput.trim() === ""}
          onclick={() => void checkHealth()}
        >
          {checkingHealth ? "检测中…" : "检测连接"}
        </button>
      </div>
      {#if health !== null}
        <p class="mt-2 text-xs text-[#6CFF00]">在线 · 数据库 {health.db}</p>
      {:else if healthError !== ""}
        <p class="mt-2 text-xs text-red-400">离线：{healthError}</p>
      {:else}
        <p class="mt-2 text-xs text-slate-600">配置云端服务器地址后可登录并同步数据。</p>
      {/if}

      {#if !loggedIn}
        <div class="mt-4 flex flex-wrap items-center gap-2">
          <input
            class="w-44 rounded border border-[#292E39] bg-[#111318] px-3 py-1.5 text-sm outline-none focus:border-[#8B51A6]"
            placeholder="用户名"
            bind:value={username}
          />
          <input
            type="password"
            class="w-44 rounded border border-[#292E39] bg-[#111318] px-3 py-1.5 text-sm outline-none focus:border-[#8B51A6]"
            placeholder="密码"
            bind:value={password}
          />
          <button
            class="rounded bg-[#6CFF00] px-4 py-1.5 text-sm font-semibold text-black hover:brightness-110 disabled:opacity-40"
            disabled={loggingIn || username.trim() === "" || password === ""}
            onclick={() => void doLogin()}
          >
            {loggingIn ? "登录中…" : "登录"}
          </button>
        </div>
        {#if authError !== ""}
          <p class="mt-2 text-xs text-red-400">{authError}</p>
        {/if}
      {/if}
    </section>

    <section class="mb-5 rounded-lg border border-[#20242C] bg-[#0D0F13] p-4">
      <h2 class="mb-3 text-xs font-semibold tracking-wider text-slate-500 uppercase">
        Local Runner
        {#if !desktop}
          <span class="ml-2 normal-case text-slate-600">（仅桌面安装包内可用）</span>
        {/if}
      </h2>
      {#if desktop}
        <div class="flex flex-wrap items-center gap-2">
          <input
            class="min-w-80 flex-1 rounded border border-[#292E39] bg-[#111318] px-3 py-1.5 text-sm outline-none focus:border-[#8B51A6]"
            placeholder="工作区根目录，例如 D:\Workspace\project"
            bind:value={workspaceRoot}
          />
          <label class="flex items-center gap-1.5 text-xs text-slate-400">
            <input type="checkbox" bind:checked={trustedMode} />
            Trusted Local Mode
          </label>
          {#if runner?.running === true}
            <button
              class="rounded border border-red-400/50 px-3 py-1.5 text-sm text-red-300 hover:bg-red-400/10 disabled:opacity-40"
              disabled={runnerBusy}
              onclick={() => void stopRunner()}
            >
              停止
            </button>
            <span class="text-xs text-[#6CFF00]">运行中 · {runner.baseUrl}</span>
          {:else}
            <button
              class="rounded bg-[#6CFF00] px-4 py-1.5 text-sm font-semibold text-black hover:brightness-110 disabled:opacity-40"
              disabled={runnerBusy || workspaceRoot.trim() === ""}
              onclick={() => void startRunner()}
            >
              启动
            </button>
            <span class="text-xs text-slate-600">未运行</span>
          {/if}
        </div>

        {#if runner?.running === true && runner.trusted === true}
          <div class="mt-4">
            <div class="mb-2 flex items-center justify-between">
              <h3 class="text-xs font-medium text-slate-400">
                待审批
                <span class="ml-2 text-slate-600">Shell / Git 高风险操作等待人工决策</span>
              </h3>
              <button
                class="rounded border border-[#292E39] px-2.5 py-1 text-xs hover:border-[#6CFF00]/50 disabled:opacity-40"
                disabled={loadingApprovals}
                onclick={() => void loadApprovals()}
              >
                刷新
              </button>
            </div>
            {#if pendingApprovals.length === 0}
              <p class="text-sm text-slate-600">当前没有待审批操作。</p>
            {:else}
              <div class="flex flex-col gap-2">
                {#each pendingApprovals as item (item.id)}
                  <div class="rounded border border-[#4A3A5C] bg-[#241B2E] p-3">
                    <div class="flex flex-wrap items-center gap-2">
                      <span class="font-mono text-sm font-semibold text-amber-300"
                        >⚠ {item.toolName}</span
                      >
                      <span class="ml-auto font-mono text-xs text-slate-600">{item.runId}</span>
                    </div>
                    <p class="mt-1 text-sm text-slate-400">{item.reason}</p>
                    <pre
                      class="mt-2 max-h-32 overflow-auto rounded border border-[#20242C] bg-[#0D0F13] p-2 font-mono text-xs text-slate-300">{JSON.stringify(item.input, null, 2)}</pre
                    >
                    <div class="mt-2 flex justify-end gap-2">
                      <button
                        class="rounded border border-red-400/50 px-3 py-1 text-xs text-red-300 hover:bg-red-400/10 disabled:opacity-40"
                        disabled={actingApprovalId !== null}
                        onclick={() => void decide(item.id, "rejected")}
                      >
                        拒绝
                      </button>
                      <button
                        class="rounded bg-[#6CFF00] px-3 py-1 text-xs font-semibold text-black hover:brightness-110 disabled:opacity-40"
                        disabled={actingApprovalId !== null}
                        onclick={() => void decide(item.id, "approved")}
                      >
                        批准
                      </button>
                    </div>
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/if}

        {#if runner?.running === true}
          <div class="mt-4">
            <div class="mb-2 flex items-center justify-between">
              <h3 class="text-xs font-medium text-slate-400">本地 Runs</h3>
              <button
                class="rounded border border-[#292E39] px-2.5 py-1 text-xs hover:border-[#6CFF00]/50 disabled:opacity-40"
                disabled={loadingLocalRuns}
                onclick={() => void loadLocalRuns()}
              >
                {loadingLocalRuns ? "加载中…" : "刷新"}
              </button>
            </div>
            {#if localRunsError !== ""}
              <p class="text-sm text-red-400">{localRunsError}</p>
            {:else if localRuns.length === 0}
              <p class="text-sm text-slate-600">
                暂无本地运行记录（历史经 SQLite 持久化，Runner 重启后保留）。
              </p>
            {:else}
              <div class="overflow-hidden rounded border border-[#20242C]">
                {#each localRuns.slice(0, 15) as run (run.id)}
                  <div
                    class="flex items-center gap-3 border-b border-[#1C2028] px-3 py-2 last:border-b-0 hover:bg-[#13161C]"
                  >
                    <span class="w-20 shrink-0 font-mono text-xs {statusColor(run.status)}"
                      >{run.status}</span
                    >
                    <span class="flex-1 truncate text-sm">{run.task}</span>
                    <span class="shrink-0 font-mono text-xs text-slate-600">{run.agentName}</span>
                  </div>
                {/each}
              </div>
            {/if}
          </div>
        {/if}
      {/if}
    </section>

    <section class="rounded-lg border border-[#20242C] bg-[#0D0F13] p-4">
      <div class="mb-3 flex items-center justify-between">
        <h2 class="text-xs font-semibold tracking-wider text-slate-500 uppercase">Runs</h2>
        {#if loggedIn}
          <button
            class="rounded border border-[#292E39] px-2.5 py-1 text-xs hover:border-[#6CFF00]/50 disabled:opacity-40"
            disabled={loadingRuns}
            onclick={() => void loadRuns()}
          >
            {loadingRuns ? "加载中…" : "刷新"}
          </button>
        {/if}
      </div>
      {#if !loggedIn}
        <p class="text-sm text-slate-600">登录后可查看云端 Runs。</p>
      {:else if runsError !== ""}
        <p class="text-sm text-red-400">{runsError}</p>
      {:else if runs.length === 0}
        <p class="text-sm text-slate-600">暂无记录——点「刷新」加载。</p>
      {:else}
              <div class="overflow-hidden rounded border border-[#20242C]">
                {#each localRuns.slice(0, 15) as run (run.id)}
                  <button
                    type="button"
                    class="flex w-full items-center gap-3 border-b border-[#1C2028] px-3 py-2 text-left last:border-b-0 hover:bg-[#13161C]"
                    onclick={() => void openRunDetail(run.id)}
                  >
                    <span class="w-20 shrink-0 font-mono text-xs {statusColor(run.status)}">{run.status}</span>
                    <span class="flex-1 truncate text-sm">{run.task}</span>
                    <span class="shrink-0 font-mono text-xs text-slate-600">{run.agentName}</span>
                  </button>
                {/each}
              </div>

              {#if selectedRunId !== null}
                <div class="mt-3 rounded border border-[#292E39] bg-[#0D0F13] p-3">
                  {#if loadingDetail}
                    <p class="text-sm text-slate-500">加载中…</p>
                  {:else if runDetailError !== ""}
                    <p class="text-sm text-red-400">{runDetailError}</p>
                  {:else if selectedRun !== null}
                    <div class="mb-2 flex flex-wrap items-center gap-2">
                      <span class="font-mono text-xs {statusColor(selectedRun.status)}"
                        >{selectedRun.status}</span
                      >
                      <span class="text-sm">{selectedRun.task}</span>
                      {#if selectedRun.status === "running" || selectedRun.status === "queued"}
                        <button
                          class="ml-auto rounded border border-red-400/50 px-2.5 py-1 text-xs text-red-300 hover:bg-red-400/10 disabled:opacity-40"
                          disabled={cancellingRun}
                          onclick={() => void cancelRun(selectedRun!.id)}
                        >
                          {cancellingRun ? "取消中…" : "取消"}
                        </button>
                      {/if}
                    </div>
                    {#if selectedRun.error !== undefined && selectedRun.error !== ""}
                      <p class="mb-2 font-mono text-xs text-red-400">{selectedRun.error}</p>
                    {/if}
                    <div class="max-h-56 overflow-y-auto rounded border border-[#20242C] bg-[#0D0F13] p-2">
                      {#if selectedRun.events.length === 0}
                        <p class="text-xs text-slate-600">（无事件）</p>
                      {:else}
                        {#each selectedRun.events as event, index (index)}
                          <div class="font-mono text-xs">
                            <span class="text-slate-600">{event.stepId ?? "—"}</span>
                            <span
                              class={event.name.startsWith("run.") ? "text-[#6CFF00]" : "text-slate-300"}
                              >{event.name}</span
                            >
                          </div>
                        {/each}
                      {/if}
                    </div>
                  {/if}
                </div>
              {/if}
      {/if}
    </section>
  </main>
</div>
